#!/usr/bin/env ruby
require 'thor'
require 'yaml'
require 'shell'
require 'fileutils'
require 'open3'

CONTEXT_CONFIG_PATH = "#{ENV["HOME"]}/workspace/.scribe-context"

class Scribe < Thor

  map '--version' => :version
  map '--help' => :help

  desc "help", "Show this help message"

  desc "context", "Set or display the available contexts"
  method_option :context , :aliases => "c" , :desc => "Context" 
  def context(new_context=nil)
    list_contexts && return if new_context.nil?

    File.open(CONTEXT_CONFIG_PATH, "r+") do |file|
      from = "(was #{current_context})" unless current_context.empty?
      puts "Changing context to #{set_color(new_context, :blue)} #{from}"

      File.truncate(file, 0)
      file.write new_context
    end
  end

  desc "story", "show git status in the repos within this context"
  def story
    unless current_context
      puts "Please set your context with `scribe context [new context name]`"
      exit 1
    end
      puts "    Here are the changes to repos in #{set_color(current_context, :green)} context:"
    each_repo do |name, repo_config|
      Dir.chdir("#{ENV["HOME"]}/workspace/#{name}")
      stdout, stdeerr, status = Open3.capture3("git status --porcelain")

      next if stdout.empty?

      puts "#{set_color(name, :green)}:"
      puts stdout
      puts
    end

  end


  no_commands do
    def list_contexts
      config.yaml.each do |context, _|
        if context == current_context
          print "* "
        else
          print "  "
        end

        puts context
      end
    end

    def each_repo
      config_hash_for_context = config.yaml[current_context]
      config_hash_for_context["repositories"].each do |repo_config|
        yield(repo_config["repository"]["name"], repo_config["repository"])
      end
    end

    def current_context
      return @current_context if @current_context
      FileUtils.touch(CONTEXT_CONFIG_PATH) unless File.exist?(CONTEXT_CONFIG_PATH)

      File.open(CONTEXT_CONFIG_PATH, "r+") do |file|
        @current_context = file.read.chomp
      end

      raise Thor::Error unless @current_context

      @current_context
    end

    def config
      return @config if @config

      @config = ScribeConfig.new
    end
  end
  # desc "coare", ""
  # def coare
  #    config.yaml[current_context]["repositories"].each do |k,v|
  #       puts k #["name"]
  #     end
  #   # puts "#{current_context}"
  # end


end

class ScribeConfig
  def yaml
    return @yaml if @yaml

    Dir.chdir("#{ENV["HOME"]}/workspace/docs-utility-scripts")
    @yaml = YAML.load_file('.scribe')
  end
end

Scribe.start(ARGV)
